name: pinn
channels:
  - conda-forge
dependencies:
  # Python stack
  - python>=3.6
  - numpy>=1.13.3
  - scipy>=1.1.0
  - matplotlib
  - tensorflow <2
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator

environment:
  PYTHONPATH:
    - {{ root }}
  PINN_UTILITIES_DIR: {{ root }}/Utilities